import { ScanRule } from './types';

/**
 * Comprehensive ruleset covering OWASP Top 10 2021
 * Each rule maps to a CWE and OWASP category.
 */
export const RULES: ScanRule[] = [
  // ── A01: Broken Access Control ──────────────────────────────────────────────
  {
    id: 'SEC001',
    name: 'Hardcoded role bypass',
    category: 'Access Control',
    severity: 'HIGH',
    owaspCategory: 'A01:2021 – Broken Access Control',
    cwe: 'CWE-284',
    pattern: /role\s*===?\s*['"]admin['"]\s*\|\||isAdmin\s*=\s*true/gi,
    message: 'Hardcoded role check detected. Use dynamic RBAC from a verified identity source.',
    remediation: 'Replace hardcoded role comparisons with a proper RBAC/ABAC system.',
  },
  {
    id: 'SEC002',
    name: 'Direct object reference without authorization',
    category: 'Access Control',
    severity: 'HIGH',
    owaspCategory: 'A01:2021 – Broken Access Control',
    cwe: 'CWE-639',
    pattern: /req\.params\.(id|userId|accountId)\b(?!.*authori[sz])/gi,
    message: 'Route parameter used directly without visible authorization check (IDOR risk).',
    remediation: 'Verify that the authenticated user owns or has permission to access the requested resource.',
  },

  // ── A02: Cryptographic Failures ─────────────────────────────────────────────
  {
    id: 'SEC010',
    name: 'Weak hash algorithm (MD5)',
    category: 'Cryptography',
    severity: 'HIGH',
    owaspCategory: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-327',
    pattern: /createHash\(['"]md5['"]\)|MD5\(|\.md5\(/gi,
    message: 'MD5 is cryptographically broken. Do not use for integrity or password hashing.',
    remediation: 'Use SHA-256 or SHA-3 for integrity checks; use bcrypt/argon2 for passwords.',
  },
  {
    id: 'SEC011',
    name: 'Weak hash algorithm (SHA1)',
    category: 'Cryptography',
    severity: 'MEDIUM',
    owaspCategory: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-327',
    pattern: /createHash\(['"]sha1['"]\)|SHA1\(/gi,
    message: 'SHA-1 is deprecated for security use.',
    remediation: 'Upgrade to SHA-256 or stronger.',
  },
  {
    id: 'SEC012',
    name: 'Hardcoded encryption key',
    category: 'Cryptography',
    severity: 'CRITICAL',
    owaspCategory: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-321',
    pattern: /(?:aes|des|cipher)\w*\s*[=:]\s*['"][A-Za-z0-9+/=]{16,}['"]/gi,
    message: 'Hardcoded encryption key found in source code.',
    remediation: 'Load encryption keys from environment variables or a secrets manager (e.g., AWS Secrets Manager, HashiCorp Vault).',
  },
  {
    id: 'SEC013',
    name: 'Disabled TLS certificate validation',
    category: 'Cryptography',
    severity: 'CRITICAL',
    owaspCategory: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-295',
    pattern: /rejectUnauthorized\s*:\s*false|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]0['"]/gi,
    message: 'TLS certificate validation is disabled, allowing MITM attacks.',
    remediation: 'Never disable certificate validation in production. Use proper CA certificates.',
  },

  // ── A03: Injection ───────────────────────────────────────────────────────────
  {
    id: 'SEC020',
    name: 'SQL injection via string concatenation',
    category: 'Injection',
    severity: 'CRITICAL',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-89',
    pattern: /(?:query|execute|raw)\s*\(\s*[`'"]\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|CREATE)\s+.*\$\{|['"`]\s*\+\s*(?:req\.|params\.|body\.|query\.)/gi,
    message: 'Possible SQL injection: user input concatenated into SQL query.',
    remediation: 'Use parameterized queries or an ORM with proper escaping.',
  },
  {
    id: 'SEC021',
    name: 'Command injection',
    category: 'Injection',
    severity: 'CRITICAL',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-78',
    pattern: /exec\s*\(\s*[`'"].*\$\{|execSync\s*\(\s*[`'"].*\$\{|child_process.*exec.*req\.|spawn\s*\(\s*req\./gi,
    message: 'Possible OS command injection: user input passed to shell execution.',
    remediation: 'Never pass user input to shell commands. Use safe APIs or allowlist validation.',
  },
  {
    id: 'SEC022',
    name: 'eval() with dynamic input',
    category: 'Injection',
    severity: 'CRITICAL',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-95',
    pattern: /\beval\s*\(\s*(?:req\.|body\.|params\.|query\.|input)/gi,
    message: 'eval() called with potentially user-controlled input.',
    remediation: 'Remove eval() usage. Use JSON.parse() for data, dedicated parsers for expressions.',
  },
  {
    id: 'SEC023',
    name: 'NoSQL injection pattern',
    category: 'Injection',
    severity: 'HIGH',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-943',
    pattern: /\$where\s*:|findOne\s*\(\s*\{[^}]*req\.|find\s*\(\s*\{[^}]*req\./gi,
    message: 'Possible NoSQL injection: user input in MongoDB query operators.',
    remediation: 'Sanitize inputs, use typed schemas (e.g., Mongoose), disallow $where.',
  },
  {
    id: 'SEC024',
    name: 'XSS via innerHTML / document.write',
    category: 'Injection',
    severity: 'HIGH',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-79',
    pattern: /\.innerHTML\s*=\s*(?!['"])|document\.write\s*\((?!['"])|dangerouslySetInnerHTML\s*=\s*\{\s*\{.*__html/gi,
    message: 'Possible XSS: unescaped content assigned to innerHTML or dangerouslySetInnerHTML.',
    remediation: 'Use textContent for plain text; use a DOM sanitizer (DOMPurify) if HTML is required.',
  },
  {
    id: 'SEC025',
    name: 'Path traversal',
    category: 'Injection',
    severity: 'HIGH',
    owaspCategory: 'A03:2021 – Injection',
    cwe: 'CWE-22',
    pattern: /(?:readFile|createReadStream|sendFile|require)\s*\([^)]*(?:req\.|params\.|body\.|query\.)[^)]*\)/gi,
    message: 'Possible path traversal: user input used in file system operations.',
    remediation: 'Validate and sanitize file paths. Use path.resolve() and verify the result is within an allowed directory.',
  },

  // ── A04: Insecure Design ─────────────────────────────────────────────────────
  {
    id: 'SEC030',
    name: 'Missing rate limiting annotation',
    category: 'Insecure Design',
    severity: 'MEDIUM',
    owaspCategory: 'A04:2021 – Insecure Design',
    cwe: 'CWE-770',
    pattern: /app\.(post|put|delete)\s*\(\s*['"][^'"]*(?:login|register|forgot|reset|auth)[^'"]*['"]/gi,
    message: 'Authentication endpoint without visible rate limiting.',
    remediation: 'Apply express-rate-limit or similar middleware to auth endpoints.',
  },

  // ── A05: Security Misconfiguration ──────────────────────────────────────────
  {
    id: 'SEC040',
    name: 'CORS wildcard origin',
    category: 'Security Misconfiguration',
    severity: 'HIGH',
    owaspCategory: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-942',
    pattern: /origin\s*:\s*['"]\*['"]|Access-Control-Allow-Origin['"]\s*:\s*['"]\*['"]/gi,
    message: 'CORS wildcard (*) origin allows any domain to make cross-origin requests.',
    remediation: 'Specify an explicit allowlist of trusted origins.',
  },
  {
    id: 'SEC041',
    name: 'Stack trace exposed to client',
    category: 'Security Misconfiguration',
    severity: 'MEDIUM',
    owaspCategory: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-209',
    pattern: /res\.(?:send|json)\s*\(\s*(?:err|error)\.stack\b|res\.status\(\d+\)\.json\s*\(\s*\{\s*stack/gi,
    message: 'Internal stack trace sent to client, leaking implementation details.',
    remediation: 'Log errors server-side only. Return a generic error message to clients.',
  },
  {
    id: 'SEC042',
    name: 'Helmet not used / security headers missing',
    category: 'Security Misconfiguration',
    severity: 'MEDIUM',
    owaspCategory: 'A05:2021 – Security Misconfiguration',
    cwe: 'CWE-693',
    pattern: /const\s+app\s*=\s*express\s*\(\s*\)(?![\s\S]{0,200}helmet)/gi,
    message: 'Express app created without helmet middleware for security headers.',
    remediation: 'Add `app.use(helmet())` early in your middleware chain.',
  },

  // ── A06: Vulnerable & Outdated Components ────────────────────────────────────
  {
    id: 'SEC050',
    name: 'Insecure deserialisation (node-serialize)',
    category: 'Vulnerable Components',
    severity: 'CRITICAL',
    owaspCategory: 'A06:2021 – Vulnerable and Outdated Components',
    cwe: 'CWE-502',
    pattern: /require\s*\(\s*['"]node-serialize['"]\s*\)|serialize\.unserialize\s*\(/gi,
    message: 'node-serialize is vulnerable to RCE via prototype pollution deserialization.',
    remediation: 'Remove node-serialize. Use JSON.parse() or a safe alternative.',
  },

  // ── A07: Identification & Authentication Failures ────────────────────────────
  {
    id: 'SEC060',
    name: 'Hardcoded JWT secret',
    category: 'Authentication',
    severity: 'CRITICAL',
    owaspCategory: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-798',
    pattern: /jwt\.sign\s*\([^,]+,\s*['"][^'"]{1,40}['"]\s*[,)]/gi,
    message: 'JWT signed with a hardcoded or short secret.',
    remediation: 'Load the JWT secret from environment variables. Use a minimum 256-bit cryptographically random secret.',
  },
  {
    id: 'SEC061',
    name: 'JWT algorithm confusion (none)',
    category: 'Authentication',
    severity: 'CRITICAL',
    owaspCategory: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-347',
    pattern: /algorithms?\s*:\s*\[\s*['"]none['"]\s*\]|verify\s*\([^)]*['"]none['"]/gi,
    message: "JWT 'none' algorithm allows bypassing signature verification.",
    remediation: "Always specify a strong algorithm (RS256 or HS256). Never accept 'none'.",
  },
  {
    id: 'SEC062',
    name: 'Weak password hashing (plain bcrypt rounds < 10)',
    category: 'Authentication',
    severity: 'MEDIUM',
    owaspCategory: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-916',
    pattern: /bcrypt\.hash\s*\([^,]+,\s*[1-9]\s*[,)]/gi,
    message: 'bcrypt cost factor below 10 is too weak for production use.',
    remediation: 'Use a cost factor of at least 12 for bcrypt.',
  },
  {
    id: 'SEC063',
    name: 'Password stored in plain text',
    category: 'Authentication',
    severity: 'CRITICAL',
    owaspCategory: 'A07:2021 – Identification and Authentication Failures',
    cwe: 'CWE-256',
    pattern: /password\s*:\s*(?:req\.body|body)\.(password|pass)\b(?!.*hash|.*bcrypt|.*argon|.*pbkdf)/gi,
    message: 'Password field stored/compared without visible hashing.',
    remediation: 'Always hash passwords with bcrypt, argon2id, or PBKDF2 before storage.',
  },

  // ── A08: Software & Data Integrity Failures ──────────────────────────────────
  {
    id: 'SEC070',
    name: 'Prototype pollution',
    category: 'Data Integrity',
    severity: 'HIGH',
    owaspCategory: 'A08:2021 – Software and Data Integrity Failures',
    cwe: 'CWE-1321',
    pattern: /\[['"]__proto__['"]\]|\[['"]constructor['"]\]\s*\[['"]prototype['"]\]|Object\.assign\s*\(\s*\{\s*\}\s*,\s*(?:req\.|body\.)/gi,
    message: 'Possible prototype pollution via user-controlled object merge.',
    remediation: 'Use Object.create(null) for safe maps. Validate keys before assignment. Use deep-merge libraries with prototype pollution protection.',
  },

  // ── A09: Security Logging & Monitoring Failures ──────────────────────────────
  {
    id: 'SEC080',
    name: 'Sensitive data logged',
    category: 'Logging',
    severity: 'MEDIUM',
    owaspCategory: 'A09:2021 – Security Logging and Monitoring Failures',
    cwe: 'CWE-532',
    pattern: /console\.\w+\s*\([^)]*(?:password|token|secret|apiKey|authorization|credit_card|ssn)\b/gi,
    message: 'Sensitive data (password/token/secret) may be written to logs.',
    remediation: 'Redact sensitive fields before logging. Use a structured logger with field masking.',
  },

  // ── A10: SSRF ────────────────────────────────────────────────────────────────
  {
    id: 'SEC090',
    name: 'Server-Side Request Forgery (SSRF)',
    category: 'SSRF',
    severity: 'HIGH',
    owaspCategory: 'A10:2021 – Server-Side Request Forgery',
    cwe: 'CWE-918',
    pattern: /(?:axios\.get|fetch|http\.get|https\.get|got)\s*\(\s*(?:req\.|body\.|params\.|query\.)/gi,
    message: 'HTTP request made with user-controlled URL (SSRF risk).',
    remediation: 'Validate URLs against an allowlist of approved hosts. Block private IP ranges (RFC 1918, loopback).',
  },

  // ── General / Misc ───────────────────────────────────────────────────────────
  {
    id: 'SEC100',
    name: 'process.env in client bundle',
    category: 'Information Exposure',
    severity: 'HIGH',
    owaspCategory: 'A02:2021 – Cryptographic Failures',
    cwe: 'CWE-200',
    pattern: /process\.env\.[A-Z_]*(?:SECRET|KEY|PASSWORD|TOKEN|API_KEY)/gi,
    message: 'Environment variable with sensitive name referenced — ensure it is not bundled into client-side code.',
    remediation: 'Keep secret env vars server-side only. Prefix public vars with NEXT_PUBLIC_ / VITE_ and audit what is bundled.',
    fileTypes: ['.ts', '.tsx', '.js', '.jsx'],
  },
];
